# **Overview**

- This notebook generates the main CSV file used as the foundation for all analyses conducted in this research.

- It processes the ZIP files located in the data folder as input.

- The output is a file named woman_not_woman_df.csv, which serves as the primary input for all subsequent tests and analyses.

In [2]:
!pip install -U kaleido
!pip install pycountry-convert

Requirement already satisfied: kaleido in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (0.2.1)
Collecting kaleido
  Downloading kaleido-1.0.0-py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.5/51.5 kB 1.2 MB/s eta 0:00:00
Collecting choreographer>=1.0.5 (from kaleido)
  Downloading choreographer-1.0.9-py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 kB 1.8 MB/s eta 0:00:00
Collecting logistro>=1.0.8 (from kaleido)
  Downloading logistro-1.1.0-py3-none-any.whl (7.9 kB)
Collecting orjson>=3.10.15 (from kaleido)
  Downloading orjson-3.11.1-cp39-cp39-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl (241 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.9/241.9 kB 5.3 MB/s eta 0:00:00[36m0:00:01
Requirement already satisfied: packaging in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (from kaleido) (23.2)
Collecting simplejson>=3.19.3 (from choreographer>=1.0.5->kaleido)
  Downloading simplejson-3.20.1-cp39-cp39-macosx_10_9_x86_64.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.7/75.7 kB 2.9 MB/s eta 0:00:00
Installing collected packages: simplejson, orjson, logistro, choreographer, kaleido
  Attempting uninstall: orjson
    Found existing installation: orjson 3.8.12
    Uninstalling orjson-3.8.12:
      Successfully uninstalled orjson-3.8.12
  Attempting uninstall: kaleido
    Found existing installation: kaleido 0.2.1
    Uninstalling kaleido-0.2.1:
      Successfully uninstalled kaleido-0.2.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pycaret 3.0.1 requires numpy<1.24,>=1.21, but you have numpy 1.24.4 which is incompatible.
Successfully installed choreographer-1.0.9 kaleido-1.0.0 logistro-1.1.0 orjson-3.11.1 simplejson-3.20.1

[notice] A new release of pip is available: 23.1.2 -> 25.2
[notice] To update, run: pip install --upgrade pip
Collecting pycountry-convert
  Downloading pycountry_convert-0.7.2-py3-none-any.whl (13 kB)
Collecting pprintpp>=0.3.0 (from pycountry-convert)
  Downloading pprintpp-0.4.0-py2.py3-none-any.whl (16 kB)
Collecting pycountry>=16.11.27.1 (from pycountry-convert)
  Downloading pycountry-24.6.1-py3-none-any.whl (6.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 15.4 MB/s eta 0:00:00m eta 0:00:010:01:01
Requirement already satisfied: pytest>=3.4.0 in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (from pycountry-convert) (7.1.2)
Collecting pytest-mock>=1.6.3 (from pycountry-convert)
  Downloading pytest_mock-3.14.1-py3-none-any.whl (9.9 kB)
Requirement already satisfied: pytest-cov>=2.5.1 in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (from pycountry-convert) (6.0.0)
Collecting repoze.lru>=0.7 (from pycountry-convert)
  Downloading repoze.lru-0.7-py3-none-any.whl (10 kB)
Requirement already satisfied: wheel>=0.30.0 in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (from pycountry-convert) (0.37.1)
Requirement already satisfied: attrs>=19.2.0 in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (25.1.0)
Requirement already satisfied: iniconfig in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (1.1.1)
Requirement already satisfied: packaging in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (23.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (1.0.0)
Requirement already satisfied: py>=1.8.2 in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (1.11.0)
Requirement already satisfied: tomli>=1.0.0 in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (from pytest>=3.4.0->pycountry-convert) (1.2.2)
Requirement already satisfied: coverage[toml]>=7.5 in /Users/arthursena/opt/miniconda3/lib/python3.9/site-packages (from pytest-cov>=2.5.1->pycountry-convert) (7.8.0)
Installing collected packages: repoze.lru, pprintpp, pycountry, pytest-mock, pycountry-convert
Successfully installed pprintpp-0.4.0 pycountry-24.6.1 pycountry-convert-0.7.2 pytest-mock-3.14.1 repoze.lru-0.7

[notice] A new release of pip is available: 23.1.2 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [4]:
# @title Unziping data
import zipfile

import re
import pycountry_convert as pc
def extract_number_from_string(string):
  pattern = r"[+]?\d*\.?\d+"
  match = re.search(pattern, string)
  if match:
    return int(match.group())
  else:
    return None

zip_files = [

    '../data/stack-overflow-developer-survey-2014.zip',
    '../data/stack-overflow-developer-survey-2015.zip',
    '../data/stack-overflow-developer-survey-2016.zip',
    '../data/stack-overflow-developer-survey-2017.zip',
    '../data/stack-overflow-developer-survey-2018.zip',
    '../data/stack-overflow-developer-survey-2019.zip',
    '../data/stack-overflow-developer-survey-2020.zip',
    '../data/stack-overflow-developer-survey-2021.zip',
    '../data/stack-overflow-developer-survey-2022.zip',]

for f in zip_files:
  with zipfile.ZipFile(f, "r") as zip_file:
    file_list = zip_file.namelist()
    year = extract_number_from_string(f)
    zip_file.extractall(f"../data/{year}_year/")
    print(f)
    print(file_list)
    print()

../data/stack-overflow-developer-survey-2014.zip
['2014 Stack Overflow Survey Responses.csv', '__MACOSX/', '__MACOSX/._2014 Stack Overflow Survey Responses.csv']

../data/stack-overflow-developer-survey-2015.zip
['2015 Stack Overflow Developer Survey Responses.csv', '__MACOSX/', '__MACOSX/._2015 Stack Overflow Developer Survey Responses.csv']

../data/stack-overflow-developer-survey-2016.zip
['2016 Stack Overflow Survey Results/', '2016 Stack Overflow Survey Results/.DS_Store', '__MACOSX/', '__MACOSX/2016 Stack Overflow Survey Results/', '__MACOSX/2016 Stack Overflow Survey Results/._.DS_Store', '2016 Stack Overflow Survey Results/2016 Stack Overflow Survey Responses.csv', '__MACOSX/2016 Stack Overflow Survey Results/._2016 Stack Overflow Survey Responses.csv', '2016 Stack Overflow Survey Results/READ_ME_-_The_Public_2016_Stack_Overflow_Developer_Survey_Results.txt', '__MACOSX/2016 Stack Overflow Survey Results/._READ_ME_-_The_Public_2016_Stack_Overflow_Developer_Survey_Results.txt']

../data/stack-overflow-developer-survey-2017.zip
['DeveloperSurvey2017QuestionaireCleaned.pdf', '__MACOSX/', '__MACOSX/._DeveloperSurvey2017QuestionaireCleaned.pdf', 'README_2017.txt', '__MACOSX/._README_2017.txt', 'survey_results_public.csv', 'survey_results_schema.csv']

../data/stack-overflow-developer-survey-2018.zip
['survey_results_public.csv', 'Developer_Survey_Instrument_2018.pdf', '__MACOSX/', '__MACOSX/._Developer_Survey_Instrument_2018.pdf', 'survey_results_schema.csv', 'README_2018.txt']

../data/stack-overflow-developer-survey-2019.zip
['survey_results_public.csv', 'survey_results_schema.csv', 'so_survey_2019.pdf', '__MACOSX/', '__MACOSX/._so_survey_2019.pdf', 'README_2019.txt', '__MACOSX/._README_2019.txt']

../data/stack-overflow-developer-survey-2020.zip
['README_2020.txt', 'so_survey_2020.pdf', 'survey_results_public.csv', 'survey_results_schema.csv']

../data/stack-overflow-developer-survey-2021.zip
['README_2021.txt', 'so_survey_2021.pdf', 'survey_results_public.csv', 'survey_results_schema.csv']

../data/stack-overflow-developer-survey-2022.zip
['README_2022.txt', 'so_survey_2022.pdf', 'survey_results_public.csv', 'survey_results_schema.csv']

In [5]:
# @title Collecting the CSV files
import os
import pandas as pd

def list_csv_files_recursively(directory_path):
  csv_file_paths = []
  for root, directories, files in os.walk(directory_path):
    for file in files:
      if file.endswith(".csv"):
        csv_file_paths.append(os.path.join(root, file))

  return csv_file_paths

file_paths = sorted([f"../data/{year}_year" for year in range(2011, 2024)])
all_dfs = {}
for path in file_paths:
  for csv_file in list_csv_files_recursively(path):
    if "__MACOSX" in csv_file or "_schema" in csv_file:
      continue
    if  "public" in csv_file or "Responses" or "Results" in csv_file:
      print(f"Reading {csv_file}")
      year =  extract_number_from_string(csv_file)
      df = None
      if year in [2011, 2012]:
        df = pd.read_csv(csv_file,encoding = "ISO-8859-1")
      else:
        df = pd.read_csv(csv_file)
      if year == 2015:
        new_header = df.iloc[0]
        df = df[1:]
        df.columns = new_header
      df["year"] = year
      all_dfs[year] = df

Reading ../data/2014_year/2014 Stack Overflow Survey Responses.csv
Reading ../data/2015_year/2015 Stack Overflow Developer Survey Responses.csv

/var/folders/t1/653ghqhd6bx77gz8c61h9lbc0000gp/T/ipykernel_36488/3822025964.py:27: DtypeWarning: Columns (5,108,121,196,197,198) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file)

Reading ../data/2016_year/2016 Stack Overflow Survey Results/2016 Stack Overflow Survey Responses.csv
Reading ../data/2017_year/survey_results_public.csv
Reading ../data/2018_year/survey_results_public.csv

/var/folders/t1/653ghqhd6bx77gz8c61h9lbc0000gp/T/ipykernel_36488/3822025964.py:27: DtypeWarning: Columns (8,12,13,14,15,16,50,51,52,53,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file)

Reading ../data/2019_year/survey_results_public.csv
Reading ../data/2020_year/survey_results_public.csv
Reading ../data/2021_year/survey_results_public.csv
Reading ../data/2022_year/survey_results_public.csv

In [7]:
'''
- Clean and merge the data
'''

def merge_dfs(all_dfs, year_to_exlude=None):
  select_cols_per_year = {
    2022 : ["year","Gender","Country","DevType","ConvertedCompYearly", "YearsCodePro", ],
    2021 : ["year","Gender","Country","DevType","ConvertedCompYearly", "YearsCodePro", ],
    2020 : ["year","Gender","Country","DevType","ConvertedComp", "YearsCodePro", ],
    2019 : ["year","Gender","Country","DevType","ConvertedComp", "YearsCodePro", ],
    2018 : ["year","Gender","Country","DevType","ConvertedSalary", "YearsCodingProf", ],
    2017 : ["year","Gender","Country","DeveloperType","Salary", "YearsProgram", ],
    2016 : ["year","gender","country","occupation_group","salary_range", "experience_range",],
    2015 : ["year","Gender","Country", "Occupation","Compensation: midpoint", "Years IT / Programming Experience", ],
    2014 : ["year","What is your gender?","Which US State or Territory do you live in?",
            "Which of the following best describes your occupation?","Including bonus, what is your annual compensation in USD?",
            "How many years of IT/Programming experience do you have?", ],
    2013 : ["year","Including bonus, what is your annual compensation in USD?"],
    2012 : ["year","Including bonus, what is your annual compensation in USD?"],
    2011 : ["year","Including bonus, what is your annual compensation in USD?"]
  }

  list_dfs = []
  colnames = ["Year", "Gender","Country","DevType", "ConvertedCompYearly", "YearsCode", ]
  for year, df in all_dfs.items():
    if year not in year_to_exlude:
      cols = select_cols_per_year[year]
      print(year)
      temp_df = df[cols]
      temp_df = temp_df.rename(
          columns={
            cols[i]:colnames[i] for i in range(len(colnames))
          }, errors="raise"
      )
      print(year, temp_df[colnames].columns, temp_df[colnames].index.is_unique)
      list_dfs.append(temp_df[colnames])

  return pd.concat(list_dfs).dropna()

def merge_genders(gender):
  # if gender in ["Male", "Man"]:
  #   return "Male"
  if ("male" in gender.lower()) and ("female" in gender.lower()) and len(gender) > 6:
    return "Not Woman"
  if (gender in ["Woman", "Female", "woman", "female"]) or "female" in gender.lower() or "woman" in gender.lower():
    return "Woman"
  if gender == "Prefer not to disclose":
    return "Prefer not to say"
  # if "non-binary" in gender.lower():
  #   return "Non-binary"
  if gender.lower() == "response" or gender.lower().strip() == "None":
    return None
  return "Not Woman"

def fix_country(country):
  state_names = ["Alaska", "Alabama", "Arkansas", "American Samoa", "Arizona", "California", "Colorado", "Connecticut",
                 "District ", "of Columbia", "Delaware", "Florida", "Georgia", "Guam", "Hawaii", "Iowa", "Idaho",
                 "Illinois", "Indiana", "Kansas", "Kentucky", "Louisiana", "Massachusetts", "Maryland", "Maine",
                 "Michigan", "Minnesota", "Missouri", "Mississippi", "Montana", "North Carolina", "North Dakota",
                 "Nebraska", "New Hampshire", "New Jersey", "New Mexico", "Nevada", "New York", "Ohio",
                 "Oklahoma", "Oregon", "Pennsylvania", "Puerto Rico", "Rhode Island", "South Carolina",
                 "South Dakota", "Tennessee",
                 "Texas", "Utah", "Virginia", "Virgin Islands", "Vermont", "Washington", "Wisconsin", "West Virginia",
                 "Washington DC","Wyoming"]
  if country.lower().strip() in ["response","none"]:
    return None
  if country.lower() in [c.lower() for c in state_names]:
    return "United States of America"
  return country

import re
def fix_salary(salary):
  if type(salary) == str:
    if salary.lower() in ["response", "rather not say", "student / unemployed", "other (please specify)"]:
      return None
    if salary.lower() == "unemployed":
      return -1
    salary=re.sub('\$|,|>|<|Less than |More than ', '', salary)
    range_salary = salary.split("-")
    if len(range_salary) == 2:
      low = float(range_salary[0].strip())
      high = float(range_salary[1].strip())
      return (low+high)/2
  return float(salary)

def country2continent(country_name):
  code2contname = {
      "EU":"Europe",
      "NA": "North America",
      "AS": "Asia",
      "SA": "South America",
      "AF": "Africa",
      "OC": "Oceania"
  }
  try:
    alpha_code = pc.map_countries()[country_name]["alpha_2"]
    continent = pc.country_alpha2_to_continent_code(alpha_code)
    return code2contname[continent]
  except:
    return None

def country2alphacode(country_name):
  import numpy as np
  try:
    alpha_code = pc.map_countries()[country_name]["alpha_3"]
    return alpha_code
  except:
    return np.nan


def process_year_of_code(x):
  if x in ["2/5/2014", "2 - 5 years"]:
    return 3.5
  if x in ["6/10/2014", "6 - 10 years"]:
    return 8
  if x in ["<2", "1 - 2 years", "Less than 1 year", "Less than a year", "0-2 years"]:
    return 1
  if x in ["11+ years"]:
    return 11
  if x in ["20 or more years"]:
    return 20
  if x in ["30 or more years"]:
    return 30
  if x in ["More than 50 years"]:
    return 50
  if "to" in x:
    return (int(x.split()[0])+int(x.split()[2]))/2
  if "-" in x and " - " not in x:
    nums = x.split()[0].split("-")
    return (int(nums[0]) + int(nums[1]))/2
  return int(x)


merged_df = merge_dfs(all_dfs, year_to_exlude=[2013, 2012, 2011, 2023])
merged_df["gender_orig"] = merged_df.Gender
merged_df["Gender"] = merged_df.Gender.apply(merge_genders)
merged_df["Country"] = merged_df.Country.apply(fix_country)
merged_df["ConvertedCompYearly"] = merged_df.ConvertedCompYearly.apply(fix_salary)
merged_df["Continent"] = merged_df.Country.apply(lambda x: country2continent(x))
merged_df["country_alpha_code"] = merged_df.Country.apply(lambda x: country2alphacode(x))
merged_df = merged_df[merged_df["ConvertedCompYearly"]>=0]
merged_df["YearsCode"] = merged_df["YearsCode"].apply(lambda x:process_year_of_code(x))
merged_df = merged_df.dropna()
merged_df["DevType"] = merged_df.DevType.str.split(";").str[0]
print("Data shape: ", merged_df.shape)

merged_df.head()

2014
2014 Index(['Year', 'Gender', 'Country', 'DevType', 'ConvertedCompYearly',
       'YearsCode'],
      dtype='object') True
2015
2015 Index(['Year', 'Gender', 'Country', 'DevType', 'ConvertedCompYearly',
       'YearsCode'],
      dtype='object', name=0) True
2016
2016 Index(['Year', 'Gender', 'Country', 'DevType', 'ConvertedCompYearly',
       'YearsCode'],
      dtype='object') True
2017
2017 Index(['Year', 'Gender', 'Country', 'DevType', 'ConvertedCompYearly',
       'YearsCode'],
      dtype='object') True
2018
2018 Index(['Year', 'Gender', 'Country', 'DevType', 'ConvertedCompYearly',
       'YearsCode'],
      dtype='object') True
2019
2019 Index(['Year', 'Gender', 'Country', 'DevType', 'ConvertedCompYearly',
       'YearsCode'],
      dtype='object') True
2020
2020 Index(['Year', 'Gender', 'Country', 'DevType', 'ConvertedCompYearly',
       'YearsCode'],
      dtype='object') True
2021
2021 Index(['Year', 'Gender', 'Country', 'DevType', 'ConvertedCompYearly',
       'YearsCode'],
      dtype='object') True
2022
2022 Index(['Year', 'Gender', 'Country', 'DevType', 'ConvertedCompYearly',
       'YearsCode'],
      dtype='object') True
Data shape:  (276298, 9)

,Year,Gender,Country,DevType,ConvertedCompYearly,YearsCode,gender_orig,Continent,country_alpha_code
18,2014,Not Woman,United States of America,Full-Stack Web Developer,140000.0,11.0,Male,North America,USA
20,2014,Woman,United States of America,Enterprise Level Services,110000.0,3.5,Female,North America,USA
23,2014,Not Woman,United States of America,Enterprise Level Services,110000.0,11.0,Male,North America,USA
27,2014,Not Woman,United States of America,Manager of Developers or Team Leader,90000.0,8.0,Male,North America,USA
30,2014,Not Woman,United States of America,IT Staff / System Administrator,70000.0,11.0,Male,North America,USA

In [9]:
import plotly.express as px
woman_not_woman_df = merged_df[merged_df.Gender.isin(["Woman", "Not Woman"])]

print("Data shape: ", woman_not_woman_df.shape)
(woman_not_woman_df
  .rename(columns={"Year": "Ano", "Gender":"Grupo", "DevType": "Cargo", "ConvertedCompYearly": "Salário Anual ($)", "Continent":"Continente", "Country": "País"})
  .drop(["country_alpha_code", "gender_orig"], axis=1).head())

Data shape:  (275867, 9)

,Ano,Grupo,País,Cargo,Salário Anual ($),YearsCode,Continente
18,2014,Not Woman,United States of America,Full-Stack Web Developer,140000.0,11.0,North America
20,2014,Woman,United States of America,Enterprise Level Services,110000.0,3.5,North America
23,2014,Not Woman,United States of America,Enterprise Level Services,110000.0,11.0,North America
27,2014,Not Woman,United States of America,Manager of Developers or Team Leader,90000.0,8.0,North America
30,2014,Not Woman,United States of America,IT Staff / System Administrator,70000.0,11.0,North America

In [10]:
woman_not_woman_df.to_csv("../data/woman_not_woman_df.csv",index=False)